name: 👸 Other
description: Use this for any other issues.
title: "[OTHER]"
labels: ["🚦 status: awaiting triage"]
body:
  - type: markdown
    attributes:
      value: "# Other issue"
  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to add a issue!
        To claim this issue, please ask for it below. 
        The maintainers will assign a contributor to this issue.
  - type: markdown
    attributes:
      value: |
         You can also join our slack community [here](https://join.slack.com/t/dokcommunity/shared_invite/zt-10v7uncvp-jNFwulsVWvUO0SKMDTjwAw)
         Feel free to check out other cool repositories of the DOK Community [here](https://github.com/dokc)