name: 👸 Other
description: Use this for any other issues.
title: "[OTHER]"
labels: ["🚦 status: awaiting triage"]
body:
  - type: markdown
    attributes:
      value: "# Other issue"
  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to add a issue!
        To claim this issue, please ask for it below. 
  - type: markdown
    attributes:
      value: |
        You can also connect with me [here](https://twitter.com/cnu1812)
        Feel free to check out other cool repositories [here](https://github.com/cnu1812)
